export const DESIGN_LIST_REQUEST = "DESIGN_LIST_REQUEST";
export const DESIGN_LIST_SUCCESS = "DESIGN_LIST_SUCCESS";
export const DESIGN_LIST_FAIL = "DESIGN_LIST_FAIL";

export const DESIGN_DETAILS_REQUEST = "DESIGN_DETAILS_REQUEST";
export const DESIGN_DETAILS_SUCCESS = "DESIGN_DETAILS_SUCCESS";
export const DESIGN_DETAILS_FAIL = "DESIGN_DETAILS_FAIL";

export const DESIGN_CREATE_REQUEST = "DESIGN_CREATE_REQUEST";
export const DESIGN_CREATE_SUCCESS = "DESIGN_CREATE_SUCCESS";
export const DESIGN_CREATE_FAIL = "DESIGN_CREATE_FAIL";
export const DESIGN_CREATE_RESET = "DESIGN_CREATE_RESET";

export const DESIGN_UPDATE_REQUEST = "DESIGN_UPDATE_REQUEST";
export const DESIGN_UPDATE_SUCCESS = "DESIGN_UPDATE_SUCCESS";
export const DESIGN_UPDATE_FAIL = "DESIGN_UPDATE_FAIL";
export const DESIGN_UPDATE_RESET = "DESIGN_UPDATE_RESET";

export const DESIGN_DELETE_REQUEST = "DESIGN_DELETE_REQUEST";
export const DESIGN_DELETE_SUCCESS = "DESIGN_DELETE_SUCCESS";
export const DESIGN_DELETE_FAIL = "DESIGN_DELETE_FAIL";
export const DESIGN_DELETE_RESET = "DESIGN_DELETE_RESET";
